[target.xtensa-esp32-none-elf]
runner = "probe-rs run --chip=esp32 --always-print-stacktrace --no-location --catch-hardfault"

[env]

[build]
target = "xtensa-esp32-none-elf"
rustflags = ["-C", "link-arg=-nostartfiles"]


[unstable]
build-std = ["alloc", "core"]
