[target.xtensa-esp32-none-elf]
# runner = "probe-rs run --chip=esp32 --always-print-stacktrace --no-location --catch-hardfault"
runner = "espflash  flash --monitor -L defmt"

[env]

[build]
target = "xtensa-esp32-none-elf"
rustflags = [
  "-C",
  "link-arg=-nostartfiles",

  # source of this linker flag 
  # https://github.com/esp-rs/no_std-training/blob/6ba7c67540334a09a41b75a11b6872f64dc7e54f/intro/defmt/.cargo/config.toml
  # i think it from esprs

  # "-C",
  # "link-arg=-Tlinkall.x",

  # Add `defmt`linking options
  "-C",
  "link-arg=-Tdefmt.x",

  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C",
  "force-frame-pointers",
]


[unstable]
build-std = ["alloc", "core"]
